Repository genexuslabs/web-controls-library, pull requests merged in 2022-11, with the labels that each got.

#275 Add Dynamic Form definition
  src/components/dynamic-form/dynamic-form-interfaces.ts
  src/components/dynamic-form/dynamic-form-renders.tsx
  src/components/dynamic-form/dynamic-form.scss
  src/components/dynamic-form/dynamic-form.tsx
  src/components/dynamic-form/readme.md
Labels: feature

#290 Add support for srcset in gx-navbar-item icon
  src/components/navbar-item/navbar-item.tsx
  src/components/navbar-item/readme.md
Labels: fix, feature

#289 Add support for Pin Show My Location property in gx-map
  src/components/map-marker/map-marker.scss
  src/components/map-marker/map-marker.tsx
  src/components/map-marker/readme.md
  src/components/map/_map-polygon-and-line-theming-mixins.scss
  src/components/map/map.scss
  src/components/map/map.tsx
  src/components/map/readme.md
Labels: fix, feature

#292 Fix for auto-complete in the gx-edit control
  src/components.d.ts
  src/components/checkbox/readme.md
  src/components/dynamic-form/readme.md
  src/components/edit/edit.tsx
  src/components/edit/readme.md
  src/components/form-field/readme.md
  src/components/icon/readme.md
  src/components/map/readme.md
  src/components/radio-group/readme.md
  src/components/radio-option/readme.md
  src/components/renders/bootstrap/edit/edit-render.scss
  src/components/select-option/readme.md
  src/components/select/readme.md
  src/components/switch/readme.md
Labels: fix

#293 Fixes for gx-card
  src/components/card-header/card-header.scss
  src/components/card/card.tsx
  src/global/common.scss
Labels: fix
