Repository genexuslabs/web-controls-library, pull requests merged in 2023-03, with the labels that each got.

#307 Fixes for gx-canvas and gx-table controls
  src/common/reserved-names.ts
  src/components/button/button.scss
  src/components/canvas-cell/canvas-cell.scss
  src/components/canvas/canvas.scss
  src/components/canvas/canvas.tsx
  src/components/canvas/readme.md
  src/components/grid-image-map/grid-image-map.scss
  src/components/table/table.scss
  src/components/table/table.tsx
  src/components/textblock/textblock.scss
  src/global/common.scss
Labels: fix

#308 Fix for Smart Grid not stretching to container size
  src/components/grid-smart-css/grid-smart-css.scss
  src/components/grid-smart-css/grid-smart-css.tsx
Labels: fix

#302 Breakpoint refactoring and layout fixes
  src/components/common/_layout-styling-config.scss
  src/components/common/interfaces.ts
  src/components/layout/layout.scss
  src/components/layout/layout.tsx
  src/components/layout/readme.md
  src/components/navbar-item/navbar-item.scss
  src/components/navbar-item/navbar-item.tsx
  src/components/navbar-item/readme.md
  src/components/navbar/navbar.scss
  src/components/navbar/navbar.tsx
  src/components/navbar/readme.md
Labels: fix

#310 Improve RTL support across all components
  src/components.d.ts
  src/components/action-sheet-item/action-sheet-item.scss
  src/components/action-sheet/action-sheet.scss
  src/components/card-header/card-header.scss
  src/components/common/_base.scss
  src/components/gauge/gauge.scss
  src/components/grid-image-map/grid-image-map.scss
  src/components/image-picker/image-picker.scss
  src/components/image/image.scss
  src/components/layout/layout.scss
  src/components/message/message.scss
  src/components/modal/modal.scss
  src/components/navbar-item/navbar-item.scss
  src/components/navbar/navbar.scss
  src/components/progress-bar/progress-bar.scss
  src/components/renders/bootstrap/card/card-render.scss
  src/components/renders/bootstrap/edit/edit-render.scss
  src/components/tab-caption/tab-caption.scss
  src/components/tab/_tab-theming-mixins.scss
  src/components/tab/tab.scss
  src/components/table-cell/table-cell.scss
  src/global/common.scss
  tests/alignment.ts
Labels: fix

#303 Optimize bundles and add more TypeScript constraints
  src/common/types.ts
  src/components.d.ts
  src/components/card-header/card-header.tsx
  src/components/common/coordsValidate.ts
  src/components/common/events/long-press.ts
  src/components/common/events/swipeable.ts
  src/components/common/highlightable.ts
  src/components/common/image-position.tsx
  src/components/common/line-clamp.ts
  src/components/common/utils.ts
  src/components/common/watch-items.ts
  src/components/dynamic-form/dynamic-form-renders.tsx
  src/components/dynamic-form/dynamic-form.tsx
  src/components/edit/edit.tsx
  src/components/gauge/gauge.tsx
  src/components/grid-flex/grid-flex.tsx
  src/components/grid-fs/grid-fs.tsx
  src/components/grid-fs/readme.md
  src/components/grid-image-map/grid-image-map.tsx
  src/components/grid-image-map/test/utils.ts
  src/components/grid-smart-css/grid-smart-css.tsx
  src/components/icon/requests.ts
  src/components/image-picker/image-picker.tsx
  src/components/image-picker/readme.md
  src/components/interactive-image/interactive-image.tsx
  src/components/lottie/lottie.tsx
  src/components/lottie/test-animation.ts
  src/components/map-circle/map-circle.tsx
  src/components/map-line/map-line.tsx
  src/components/map-marker/map-marker.tsx
  src/components/map-polygon/map-polygon.tsx
  src/components/map/geolocation.ts
  src/components/map/map.tsx
  src/components/navbar/navbar.tsx
  src/components/query-viewer/query-viewer.tsx
  src/components/renders/bootstrap/checkbox/checkbox-render.tsx
  src/components/renders/bootstrap/edit/edit-render.tsx
  src/components/renders/bootstrap/select/select-render.tsx
  src/components/select/select.tsx
  src/components/video/video.tsx
  stencil.config.ts
  tests/alignment.ts
  tsconfig.json
Labels: fix

#312 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#311 Add vscode settings to improve code formating
  .vscode/settings.json
Labels: fix

#317 Improve repository settings
  .eslintrc.js
  .prettierrc.json
  package-lock.json
  package.json
  src/components/button/button.tsx
  src/components/canvas-cell/canvas-cell.tsx
  src/components/canvas/canvas.tsx
  src/components/card-header/readme.md
  src/components/card/readme.md
  src/components/chronometer/chronometer.tsx
  src/components/chronometer/readme.md
  src/components/common/css-transforms/css-transforms.ts
  src/components/common/css-variables-watcher.ts
  src/components/common/events/long-press.ts
  src/components/common/line-clamp.ts
  src/components/common/utils.ts
  src/components/dynamic-form/dynamic-form-renders.tsx
  src/components/dynamic-form/dynamic-form.tsx
  src/components/form-field/form-field.tsx
  src/components/gauge-range/gauge-range.tsx
  src/components/gauge/gauge.tsx
  src/components/grid-flex/grid-flex.tsx
  src/components/grid-fs/grid-fs.tsx
  src/components/grid-horizontal/grid-horizontal.tsx
  src/components/grid-image-map/grid-image-map.tsx
  src/components/grid-infinite-scroll/grid-infinite-scroll.tsx
  src/components/grid-smart-cell/grid-smart-cell.tsx
  src/components/grid-smart-css/grid-smart-css.tsx
  src/components/header-row-pattern-marker/header-row-pattern-marker.tsx
  src/components/icon/icon.tsx
  src/components/image-picker/image-picker.tsx
  src/components/image/image.tsx
  src/components/interactive-image/interactive-image.tsx
  src/components/interactive-image/readme.md
  src/components/loading/loading.tsx
  src/components/lottie/lottie.tsx
  src/components/map-marker/map-marker.tsx
  src/components/map/map.tsx
  src/components/message/message.tsx
  src/components/modal/modal.tsx
  src/components/modal/readme.md
  src/components/navbar/navbar.tsx
  src/components/password-edit/password-edit.tsx
  src/components/query-viewer-element/query-viewer-element.tsx
  src/components/query-viewer-elements-format-style/query-viewer-format-style.tsx
  src/components/query-viewer-elements-format/query-viewer-elements-format.tsx
  src/components/query-viewer-parameter/query-viewer-parameter.tsx
  src/components/query-viewer/query-viewer.tsx
  src/components/radio-group/radio-group.tsx
  src/components/radio-option/radio-option.tsx
  src/components/rating/rating.tsx
  src/components/renders/bootstrap/edit/edit-render.tsx
  src/components/select/select.tsx
  src/components/tab-caption/tab-caption.tsx
  src/components/tab/readme.md
  src/components/tab/tab.tsx
  src/components/table-cell/table-cell.tsx
  src/components/table/table.tsx
  src/components/textblock/textblock.tsx
  tests/alignment.ts
Labels: enhancement, fix

#309 Fixes and improvements for Map components
  package-lock.json
  package.json
  src/components.d.ts
  src/components/common/coordsValidate.ts
  src/components/common/interfaces.ts
  src/components/edit/edit.scss
  src/components/form-field/form-field.scss
  src/components/map-circle/map-circle.tsx
  src/components/map-circle/readme.md
  src/components/map-line/map-line.tsx
  src/components/map-line/readme.md
  src/components/map-marker/map-marker.tsx
  src/components/map-marker/readme.md
  src/components/map-polygon/map-polygon.tsx
  src/components/map-polygon/readme.md
  src/components/map/_map-marker-cluster.scss
  src/components/map/map.e2e.ts
  src/components/map/map.scss
  src/components/map/map.tsx
  src/components/map/readme.md
Labels: fix, feature

#315 House keeping
  src/components/common/_image-position.scss
  src/components/common/base-component.tsx
  src/components/common/image-position.tsx
  src/components/renders/bootstrap/card/card-render.scss
  src/components/renders/bootstrap/card/card-render.tsx
Labels: fix

#313 Add message for recommended extensions when starting vscode
  .vscode/extensions.json
Labels: enhancement

#319 Move the controls tests to their respective `test` folder
  src/components/action-sheet-item/test/action-sheet-item.e2e.ts
  src/components/action-sheet/test/action-sheet.e2e.ts
  src/components/button/test/button-height.e2e.ts
  src/components/button/test/button-width.e2e.ts
  src/components/button/test/button.e2e.ts
  src/components/canvas/test/canvas.e2e.ts
  src/components/card/test/card.e2e.ts
  src/components/chronometer/test/chronometer.e2e.ts
  src/components/form-field/test/form-field.e2e.ts
  src/components/gauge/test/gauge.e2e.ts
  src/components/group/test/group.e2e.ts
  src/components/header-row-pattern-marker/test/header-row-pattern-marker.e2e.ts
  src/components/icon/test/icon.e2e.ts
  src/components/image/test/image-align.e2e.ts
  src/components/image/test/image.e2e.ts
  src/components/interactive-image/test/interactive-image.e2e.ts
  src/components/layout/test/layout.e2e.ts
  src/components/loading/test/loading.e2e.ts
  src/components/lottie/test/lottie.e2e.ts
  src/components/map-marker/test/map-marker.e2e.ts
  src/components/map/test/map.e2e.ts
  src/components/message/test/message.e2e.ts
  src/components/modal/test/modal.e2e.ts
  src/components/navbar-item/test/navbar-item.e2e.ts
  src/components/navbar/test/navbar.e2e.ts
  src/components/progress-bar/test/progress-bar.e2e.ts
  src/components/rating/test/rating.e2e.ts
  src/components/renders/bootstrap/checkbox/test/checkbox.e2e.ts
  src/components/renders/bootstrap/edit/test/edit-datetime-local.e2e.ts
  src/components/renders/bootstrap/edit/test/edit-html.e2e.ts
  src/components/renders/bootstrap/edit/test/edit-multiline.e2e.ts
  src/components/renders/bootstrap/edit/test/edit-number.e2e.ts
  src/components/renders/bootstrap/edit/test/edit-text.e2e.ts
  src/components/renders/bootstrap/edit/test/edit.e2e.ts
  src/components/renders/bootstrap/password-edit/test/password-edit.e2e.ts
  src/components/renders/bootstrap/radio-option/test/radio-option.e2e.ts
  src/components/renders/bootstrap/select/test/select.e2e.ts
  src/components/switch/test/switch.e2e.ts
  src/components/tab-caption/test/tab-caption.e2e.ts
  src/components/tab/test/tab.e2e.ts
  src/components/table-cell/test/table-cell.e2e.ts
  src/components/table/test/table.e2e.ts
  src/components/textblock/test/textblock-autogrow.e2e.ts
  src/components/textblock/test/textblock.e2e.ts
Labels: enhancement

#318 Improve linter settings
  .eslintrc.js
  src/components/canvas/canvas.tsx
  src/components/chronometer/chronometer.tsx
  src/components/common/css-transforms/css-transforms.ts
  src/components/common/line-clamp.ts
  src/components/common/motion-handlers/dismissable.ts
  src/components/common/utils.ts
  src/components/dynamic-form/dynamic-form-renders.tsx
  src/components/dynamic-form/dynamic-form.tsx
  src/components/edit/edit.tsx
  src/components/form-field/form-field.tsx
  src/components/gauge/gauge.tsx
  src/components/gauge/test/gauge.e2e.ts
  src/components/grid-flex/grid-flex.tsx
  src/components/grid-image-map-item/grid-image-map-item.tsx
  src/components/grid-image-map-item/test/grid-image-map-item.e2e.ts
  src/components/grid-image-map/grid-image-map.tsx
  src/components/grid-image-map/test/grid-image-map.e2e.ts
  src/components/grid-image-map/test/utils.ts
  src/components/grid-infinite-scroll/grid-infinite-scroll.tsx
  src/components/grid-smart-css/grid-smart-css.tsx
  src/components/image-picker/image-picker.tsx
  src/components/loading/loading.tsx
  src/components/map/map.tsx
  src/components/map/test/map.e2e.ts
  src/components/message/message.tsx
  src/components/modal/modal.tsx
  src/components/progress-bar/progress-bar.tsx
  src/components/renders/bootstrap/edit/edit-render.tsx
  src/components/tab/tab.tsx
Labels: enhancement

#320 Enforce consistent brace style for all control statements
  .eslintrc.js
  src/components/dynamic-form/dynamic-form.tsx
Labels: enhancement

#316 Separate the navbar's JS from the main bundle
  stencil.config.ts
Labels: enhancement
